"use client";

import { Button } from "@/components/ui/Button";
import { useEffect, useState } from "react";

const KEY = "stockline_onboarding_done_v1";

const STEPS = [
  {
    title: "Deposit stocks",
    body: "Use tokenized equities as collateral. You keep your market exposure.",
  },
  {
    title: "Borrow USDC",
    body: "Unlock liquidity without selling. Borrow against what you already hold.",
  },
  {
    title: "Repay with yield",
    body: "Money generated by your assets can automatically pay down your debt.",
  },
];

export function Onboarding({ onDone }: { onDone: () => void }) {
  const [step, setStep] = useState(0);
  const current = STEPS[step];
  const isLast = step === STEPS.length - 1;

  const finish = () => {
    localStorage.setItem(KEY, "1");
    onDone();
  };

  return (
    <div className="fixed inset-0 z-[60] flex flex-col bg-[var(--bg)] px-6 py-8 sm:px-10">
      <div className="mx-auto flex w-full max-w-lg flex-1 flex-col">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[var(--lime)] text-sm font-extrabold text-[var(--bg)]">
              S
            </span>
            <span className="font-semibold">Stockline</span>
          </div>
          <button
            onClick={finish}
            className="text-sm font-medium text-[var(--ink-muted)] hover:text-[var(--ink)]"
          >
            Skip
          </button>
        </div>

        <div className="flex flex-1 flex-col justify-center gap-4 py-12">
          <p className="text-sm font-semibold tracking-wide text-[var(--lime)]">
            {step + 1} / {STEPS.length}
          </p>
          <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
            {current.title}
          </h1>
          <p className="max-w-md text-base leading-relaxed text-[var(--ink-muted)]">
            {current.body}
          </p>
          <div className="mt-6 flex gap-2">
            {STEPS.map((_, i) => (
              <span
                key={i}
                className={`h-2 rounded-full transition-all ${
                  i === step
                    ? "w-6 bg-[var(--lime)]"
                    : "w-2 bg-[var(--border-strong)]"
                }`}
              />
            ))}
          </div>
        </div>

        <div className="flex gap-3">
          {step > 0 ? (
            <Button
              variant="ghost"
              className="flex-1"
              onClick={() => setStep((s) => s - 1)}
            >
              Back
            </Button>
          ) : (
            <div className="flex-1" />
          )}
          <Button
            className="flex-[1.4]"
            onClick={() => {
              if (isLast) finish();
              else setStep((s) => s + 1);
            }}
          >
            {isLast ? "Get started" : "Next"}
          </Button>
        </div>
      </div>
    </div>
  );
}

export function useNeedsOnboarding() {
  const [ready, setReady] = useState(false);
  const [needs, setNeeds] = useState(false);

  useEffect(() => {
    setNeeds(localStorage.getItem(KEY) !== "1");
    setReady(true);
  }, []);

  return { ready, needs, clear: () => setNeeds(false) };
}
