export const ONBOARDING_KEY = "stockline_onboarding_done_v1";

export const ONBOARDING_STEPS = [
  {
    id: "deposit",
    title: "Deposit stocks",
    body: "Use tokenized equities as collateral. You keep your market exposure.",
  },
  {
    id: "borrow",
    title: "Borrow USDC",
    body: "Unlock liquidity without selling. Borrow against what you already hold.",
  },
  {
    id: "repay",
    title: "Repay with yield",
    body: "Money generated by your assets can automatically pay down your debt.",
  },
] as const;
